// <auto-generated>
// SPDX-License-Identifier: MPL-2.0
namespace Escapey.Sprites;

/// <summary>Defines all sprites.</summary>
[Sprite("Sprites")]
sealed partial class Sprite
{
    /// <summary>Defines arm sprites.</summary>
    public static class Arm
    {
        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/">Directory</a></summary>
        [Sprite("arm l", FrameRate = 10)]
        public enum Left : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/end/1.png">Images</a></summary>
            [Sprite("end", Frames = 4)]
            Neutral,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/1/1.png">Images</a></summary>
            [Sprite("1", Frames = 3)]
            Outer,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/3/1.png">Images</a></summary>
            [Sprite("3", Frames = 3)]
            Inner,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/2/1.png">Images</a></summary>
            [Sprite("2", Frames = 3)]
            Both,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm l/idle/1.png">Images</a></summary>
            [Sprite("idle", Frames = 2, FrameRate = 2, Loops = true)]
            Idle,
        }

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/">Directory</a></summary>
        [Sprite("arm r", FrameRate = 10)]
        public enum Right : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/end/1.png">Images</a></summary>
            [Sprite("end", Frames = 4)]
            Neutral,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/3/1.png">Images</a></summary>
            [Sprite("3", Frames = 3)]
            Inner,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/1/1.png">Images</a></summary>
            [Sprite("1", Frames = 3)]
            Outer,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/2/1.png">Images</a></summary>
            [Sprite("2", Frames = 3)]
            Both,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/arm r/idle/1.png">Images</a></summary>
            [Sprite("idle", Frames = 2, FrameRate = 2, Loops = true)]
            Idle,
        }
    }

    /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/body anims/">Directory</a></summary>
    [Sprite("body anims")]
    public enum Body : byte
    {
        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/body anims/end/1.png">Images</a></summary>
        [Sprite("end", Frames = 3)]
        Neutral,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/body anims/type/1.png">Images</a></summary>
        [Sprite("type", Frames = 3)]
        Typing,
    }

    /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/">Directory</a></summary>
    [Sprite("expressions/eyes")]
    public enum Eyes : byte
    {
        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/angry.png">Image</a></summary>
        [Sprite("angry")]
        Angry,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/bored.png">Image</a></summary>
        [Sprite("bored")]
        Bored,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/concentrated.png">Image</a></summary>
        [Sprite("concentrated")]
        Concentrated,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/confused.png">Image</a></summary>
        [Sprite("confused")]
        Confused,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/frown.png">Image</a></summary>
        [Sprite("frown")]
        Frown,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/happy.png">Image</a></summary>
        [Sprite("happy")]
        Happy,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/happy eyebrow.png">Image</a></summary>
        [Sprite("happy eyebrow")]
        HappyEyebrow,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/scared.png">Image</a></summary>
        [Sprite("scared")]
        Scared,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/eyes/upset.png">Image</a></summary>
        [Sprite("upset")]
        Upset,
    }

    /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/keys/">Directory</a></summary>
    [Sprite("keys")]
    public static class Keys
    {
        /// <summary>Defines the keyboard base sprite.</summary>
        public enum Background : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/under.png">Image</a></summary>
            [Sprite("under")]
            Neutral,
        }

        /// <summary>Defines actively pressed key sprites.</summary>
        public enum First : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys1/1.png">Images</a></summary>
            [Sprite("keys1/1")]
            FirstPerson,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys2/1.png">Images</a></summary>
            [Sprite("keys2/1")]
            SecondPerson,
        }

        /// <summary>Defines actively pressed key sprites.</summary>
        public enum Fourth : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys1/4.png">Images</a></summary>
            [Sprite("keys1/4")]
            FirstPerson,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys2/4.png">Images</a></summary>
            [Sprite("keys2/4")]
            SecondPerson,
        }

        /// <summary>Defines the keyboard overlay sprite.</summary>
        public enum Overlay : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/overlay.png">Image</a></summary>
            [Sprite("overlay")]
            Neutral,
        }

        /// <summary>Defines actively pressed key sprites.</summary>
        public enum Second : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys1/2.png">Images</a></summary>
            [Sprite("keys1/2")]
            FirstPerson,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys2/2.png">Images</a></summary>
            [Sprite("keys2/2")]
            SecondPerson,
        }

        /// <summary>Defines actively pressed key sprites.</summary>
        public enum Third : byte
        {
            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys1/3.png">Images</a></summary>
            [Sprite("keys1/3")]
            FirstPerson,

            /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites//keys/keys2/3.png">Images</a></summary>
            [Sprite("keys2/3")]
            SecondPerson,
        }
    }

    /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/legs/">Directory</a></summary>
    public enum Legs : byte
    {
        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/legs/1.png">Images</a></summary>
        [Sprite("legs", Frames = 2, FrameRate = 2, Loops = true)]
        Neutral,
    }

    /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/">Directory</a> or <a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/">other directory</a>.</summary>
    [Sprite(FrameRate = 15)]
    public enum Mouth : byte
    {
        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/angry.png">Image</a></summary>
        [Sprite("expressions/mouths/angry")]
        Angry,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/bored.png">Image</a></summary>
        [Sprite("expressions/mouths/bored")]
        Bored,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/concentrated.png">Image</a></summary>
        [Sprite("expressions/mouths/concentrated")]
        Concentrated,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/confused.png">Image</a></summary>
        [Sprite("expressions/mouths/confused")]
        Confused,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/frown.png">Image</a></summary>
        [Sprite("expressions/mouths/frown")]
        Frown,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/happy.png">Image</a></summary>
        [Sprite("expressions/mouths/happy")]
        Happy,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/happy eyebrow.png">Image</a></summary>
        [Sprite("expressions/mouths/happy eyebrow")]
        HappyEyebrow,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/scared.png">Image</a></summary>
        [Sprite("expressions/mouths/scared")]
        Scared,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/expressions/mouths/upset.png">Image</a></summary>
        [Sprite("expressions/mouths/upset")]
        Upset,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/ah/1.png">Images</a></summary>
        [Sprite("lipsync/ah", Frames = 6)]
        Ah,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/dz/1.png">Images</a></summary>
        [Sprite("lipsync/dz", Frames = 8)]
        Dz,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/e/1.png">Images</a></summary>
        [Sprite("lipsync/e", Frames = 6)]
        E,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/f/1.png">Images</a></summary>
        [Sprite("lipsync/f", Frames = 6)]
        F,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/m/1.png">Images</a></summary>
        [Sprite("lipsync/m", Frames = 6)]
        M,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/nsl/1.png">Images</a></summary>
        [Sprite("lipsync/nsl", Frames = 8)]
        Nsl,

        /// <summary><a href="file:///home/emik/RiderProjects/Escapey/Content/Sprites/lipsync/o/1.png">Images</a></summary>
        [Sprite("lipsync/o", Frames = 6)]
        O,
    }
}
