// <auto-generated>
// SPDX-License-Identifier: MPL-2.0
namespace Escapey.ML;

/// <summary>The input class for <see cref="HearMonitor"/>.</summary>
sealed class AudioSegment
{
    /// <summary>The inlined array.</summary>
    [InlineArray(IAudioProvider.Length)]
    public struct Array
    {
        /// <summary>The first element of the buffer.</summary>
        float _head;

        /// <inheritdoc cref="Span{T}.CopyTo"/>
        public void CopyTo(Span<float> destination) => ((ReadOnlySpan<float>)this).CopyTo(destination);
    }

    /// <summary>The inlined array.</summary>
    Array _array;

    /// <summary>Gets the first element of the buffer.</summary>
    [NoColumn]
    public ref float Head => ref _array[0];

    /// <summary>Gets or sets the normalization factor.</summary>
    public float NormalizationFactor { get; set; }

    /// <summary>Gets or sets the predicted label. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public int PredictedLabel { get; set; }

    /// <summary>Gets or sets the label. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float Label { get; set; }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E0
    {
        get => _array[0];
        set => _array[0] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E1
    {
        get => _array[1];
        set => _array[1] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E2
    {
        get => _array[2];
        set => _array[2] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E3
    {
        get => _array[3];
        set => _array[3] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E4
    {
        get => _array[4];
        set => _array[4] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E5
    {
        get => _array[5];
        set => _array[5] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E6
    {
        get => _array[6];
        set => _array[6] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E7
    {
        get => _array[7];
        set => _array[7] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E8
    {
        get => _array[8];
        set => _array[8] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E9
    {
        get => _array[9];
        set => _array[9] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E10
    {
        get => _array[10];
        set => _array[10] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E11
    {
        get => _array[11];
        set => _array[11] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E12
    {
        get => _array[12];
        set => _array[12] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E13
    {
        get => _array[13];
        set => _array[13] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E14
    {
        get => _array[14];
        set => _array[14] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E15
    {
        get => _array[15];
        set => _array[15] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E16
    {
        get => _array[16];
        set => _array[16] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E17
    {
        get => _array[17];
        set => _array[17] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E18
    {
        get => _array[18];
        set => _array[18] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E19
    {
        get => _array[19];
        set => _array[19] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E20
    {
        get => _array[20];
        set => _array[20] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E21
    {
        get => _array[21];
        set => _array[21] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E22
    {
        get => _array[22];
        set => _array[22] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E23
    {
        get => _array[23];
        set => _array[23] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E24
    {
        get => _array[24];
        set => _array[24] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E25
    {
        get => _array[25];
        set => _array[25] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E26
    {
        get => _array[26];
        set => _array[26] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E27
    {
        get => _array[27];
        set => _array[27] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E28
    {
        get => _array[28];
        set => _array[28] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E29
    {
        get => _array[29];
        set => _array[29] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E30
    {
        get => _array[30];
        set => _array[30] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E31
    {
        get => _array[31];
        set => _array[31] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E32
    {
        get => _array[32];
        set => _array[32] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E33
    {
        get => _array[33];
        set => _array[33] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E34
    {
        get => _array[34];
        set => _array[34] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E35
    {
        get => _array[35];
        set => _array[35] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E36
    {
        get => _array[36];
        set => _array[36] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E37
    {
        get => _array[37];
        set => _array[37] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E38
    {
        get => _array[38];
        set => _array[38] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E39
    {
        get => _array[39];
        set => _array[39] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E40
    {
        get => _array[40];
        set => _array[40] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E41
    {
        get => _array[41];
        set => _array[41] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E42
    {
        get => _array[42];
        set => _array[42] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E43
    {
        get => _array[43];
        set => _array[43] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E44
    {
        get => _array[44];
        set => _array[44] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E45
    {
        get => _array[45];
        set => _array[45] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E46
    {
        get => _array[46];
        set => _array[46] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E47
    {
        get => _array[47];
        set => _array[47] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E48
    {
        get => _array[48];
        set => _array[48] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E49
    {
        get => _array[49];
        set => _array[49] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E50
    {
        get => _array[50];
        set => _array[50] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E51
    {
        get => _array[51];
        set => _array[51] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E52
    {
        get => _array[52];
        set => _array[52] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E53
    {
        get => _array[53];
        set => _array[53] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E54
    {
        get => _array[54];
        set => _array[54] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E55
    {
        get => _array[55];
        set => _array[55] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E56
    {
        get => _array[56];
        set => _array[56] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E57
    {
        get => _array[57];
        set => _array[57] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E58
    {
        get => _array[58];
        set => _array[58] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E59
    {
        get => _array[59];
        set => _array[59] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E60
    {
        get => _array[60];
        set => _array[60] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E61
    {
        get => _array[61];
        set => _array[61] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E62
    {
        get => _array[62];
        set => _array[62] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E63
    {
        get => _array[63];
        set => _array[63] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E64
    {
        get => _array[64];
        set => _array[64] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E65
    {
        get => _array[65];
        set => _array[65] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E66
    {
        get => _array[66];
        set => _array[66] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E67
    {
        get => _array[67];
        set => _array[67] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E68
    {
        get => _array[68];
        set => _array[68] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E69
    {
        get => _array[69];
        set => _array[69] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E70
    {
        get => _array[70];
        set => _array[70] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E71
    {
        get => _array[71];
        set => _array[71] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E72
    {
        get => _array[72];
        set => _array[72] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E73
    {
        get => _array[73];
        set => _array[73] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E74
    {
        get => _array[74];
        set => _array[74] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E75
    {
        get => _array[75];
        set => _array[75] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E76
    {
        get => _array[76];
        set => _array[76] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E77
    {
        get => _array[77];
        set => _array[77] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E78
    {
        get => _array[78];
        set => _array[78] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E79
    {
        get => _array[79];
        set => _array[79] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E80
    {
        get => _array[80];
        set => _array[80] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E81
    {
        get => _array[81];
        set => _array[81] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E82
    {
        get => _array[82];
        set => _array[82] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E83
    {
        get => _array[83];
        set => _array[83] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E84
    {
        get => _array[84];
        set => _array[84] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E85
    {
        get => _array[85];
        set => _array[85] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E86
    {
        get => _array[86];
        set => _array[86] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E87
    {
        get => _array[87];
        set => _array[87] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E88
    {
        get => _array[88];
        set => _array[88] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E89
    {
        get => _array[89];
        set => _array[89] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E90
    {
        get => _array[90];
        set => _array[90] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E91
    {
        get => _array[91];
        set => _array[91] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E92
    {
        get => _array[92];
        set => _array[92] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E93
    {
        get => _array[93];
        set => _array[93] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E94
    {
        get => _array[94];
        set => _array[94] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E95
    {
        get => _array[95];
        set => _array[95] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E96
    {
        get => _array[96];
        set => _array[96] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E97
    {
        get => _array[97];
        set => _array[97] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E98
    {
        get => _array[98];
        set => _array[98] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E99
    {
        get => _array[99];
        set => _array[99] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E100
    {
        get => _array[100];
        set => _array[100] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E101
    {
        get => _array[101];
        set => _array[101] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E102
    {
        get => _array[102];
        set => _array[102] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E103
    {
        get => _array[103];
        set => _array[103] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E104
    {
        get => _array[104];
        set => _array[104] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E105
    {
        get => _array[105];
        set => _array[105] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E106
    {
        get => _array[106];
        set => _array[106] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E107
    {
        get => _array[107];
        set => _array[107] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E108
    {
        get => _array[108];
        set => _array[108] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E109
    {
        get => _array[109];
        set => _array[109] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E110
    {
        get => _array[110];
        set => _array[110] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E111
    {
        get => _array[111];
        set => _array[111] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E112
    {
        get => _array[112];
        set => _array[112] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E113
    {
        get => _array[113];
        set => _array[113] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E114
    {
        get => _array[114];
        set => _array[114] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E115
    {
        get => _array[115];
        set => _array[115] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E116
    {
        get => _array[116];
        set => _array[116] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E117
    {
        get => _array[117];
        set => _array[117] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E118
    {
        get => _array[118];
        set => _array[118] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E119
    {
        get => _array[119];
        set => _array[119] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E120
    {
        get => _array[120];
        set => _array[120] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E121
    {
        get => _array[121];
        set => _array[121] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E122
    {
        get => _array[122];
        set => _array[122] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E123
    {
        get => _array[123];
        set => _array[123] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E124
    {
        get => _array[124];
        set => _array[124] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E125
    {
        get => _array[125];
        set => _array[125] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E126
    {
        get => _array[126];
        set => _array[126] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E127
    {
        get => _array[127];
        set => _array[127] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E128
    {
        get => _array[128];
        set => _array[128] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E129
    {
        get => _array[129];
        set => _array[129] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E130
    {
        get => _array[130];
        set => _array[130] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E131
    {
        get => _array[131];
        set => _array[131] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E132
    {
        get => _array[132];
        set => _array[132] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E133
    {
        get => _array[133];
        set => _array[133] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E134
    {
        get => _array[134];
        set => _array[134] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E135
    {
        get => _array[135];
        set => _array[135] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E136
    {
        get => _array[136];
        set => _array[136] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E137
    {
        get => _array[137];
        set => _array[137] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E138
    {
        get => _array[138];
        set => _array[138] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E139
    {
        get => _array[139];
        set => _array[139] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E140
    {
        get => _array[140];
        set => _array[140] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E141
    {
        get => _array[141];
        set => _array[141] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E142
    {
        get => _array[142];
        set => _array[142] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E143
    {
        get => _array[143];
        set => _array[143] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E144
    {
        get => _array[144];
        set => _array[144] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E145
    {
        get => _array[145];
        set => _array[145] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E146
    {
        get => _array[146];
        set => _array[146] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E147
    {
        get => _array[147];
        set => _array[147] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E148
    {
        get => _array[148];
        set => _array[148] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E149
    {
        get => _array[149];
        set => _array[149] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E150
    {
        get => _array[150];
        set => _array[150] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E151
    {
        get => _array[151];
        set => _array[151] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E152
    {
        get => _array[152];
        set => _array[152] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E153
    {
        get => _array[153];
        set => _array[153] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E154
    {
        get => _array[154];
        set => _array[154] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E155
    {
        get => _array[155];
        set => _array[155] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E156
    {
        get => _array[156];
        set => _array[156] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E157
    {
        get => _array[157];
        set => _array[157] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E158
    {
        get => _array[158];
        set => _array[158] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E159
    {
        get => _array[159];
        set => _array[159] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E160
    {
        get => _array[160];
        set => _array[160] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E161
    {
        get => _array[161];
        set => _array[161] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E162
    {
        get => _array[162];
        set => _array[162] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E163
    {
        get => _array[163];
        set => _array[163] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E164
    {
        get => _array[164];
        set => _array[164] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E165
    {
        get => _array[165];
        set => _array[165] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E166
    {
        get => _array[166];
        set => _array[166] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E167
    {
        get => _array[167];
        set => _array[167] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E168
    {
        get => _array[168];
        set => _array[168] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E169
    {
        get => _array[169];
        set => _array[169] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E170
    {
        get => _array[170];
        set => _array[170] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E171
    {
        get => _array[171];
        set => _array[171] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E172
    {
        get => _array[172];
        set => _array[172] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E173
    {
        get => _array[173];
        set => _array[173] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E174
    {
        get => _array[174];
        set => _array[174] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E175
    {
        get => _array[175];
        set => _array[175] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E176
    {
        get => _array[176];
        set => _array[176] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E177
    {
        get => _array[177];
        set => _array[177] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E178
    {
        get => _array[178];
        set => _array[178] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E179
    {
        get => _array[179];
        set => _array[179] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E180
    {
        get => _array[180];
        set => _array[180] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E181
    {
        get => _array[181];
        set => _array[181] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E182
    {
        get => _array[182];
        set => _array[182] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E183
    {
        get => _array[183];
        set => _array[183] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E184
    {
        get => _array[184];
        set => _array[184] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E185
    {
        get => _array[185];
        set => _array[185] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E186
    {
        get => _array[186];
        set => _array[186] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E187
    {
        get => _array[187];
        set => _array[187] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E188
    {
        get => _array[188];
        set => _array[188] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E189
    {
        get => _array[189];
        set => _array[189] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E190
    {
        get => _array[190];
        set => _array[190] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E191
    {
        get => _array[191];
        set => _array[191] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E192
    {
        get => _array[192];
        set => _array[192] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E193
    {
        get => _array[193];
        set => _array[193] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E194
    {
        get => _array[194];
        set => _array[194] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E195
    {
        get => _array[195];
        set => _array[195] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E196
    {
        get => _array[196];
        set => _array[196] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E197
    {
        get => _array[197];
        set => _array[197] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E198
    {
        get => _array[198];
        set => _array[198] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E199
    {
        get => _array[199];
        set => _array[199] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E200
    {
        get => _array[200];
        set => _array[200] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E201
    {
        get => _array[201];
        set => _array[201] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E202
    {
        get => _array[202];
        set => _array[202] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E203
    {
        get => _array[203];
        set => _array[203] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E204
    {
        get => _array[204];
        set => _array[204] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E205
    {
        get => _array[205];
        set => _array[205] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E206
    {
        get => _array[206];
        set => _array[206] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E207
    {
        get => _array[207];
        set => _array[207] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E208
    {
        get => _array[208];
        set => _array[208] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E209
    {
        get => _array[209];
        set => _array[209] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E210
    {
        get => _array[210];
        set => _array[210] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E211
    {
        get => _array[211];
        set => _array[211] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E212
    {
        get => _array[212];
        set => _array[212] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E213
    {
        get => _array[213];
        set => _array[213] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E214
    {
        get => _array[214];
        set => _array[214] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E215
    {
        get => _array[215];
        set => _array[215] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E216
    {
        get => _array[216];
        set => _array[216] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E217
    {
        get => _array[217];
        set => _array[217] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E218
    {
        get => _array[218];
        set => _array[218] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E219
    {
        get => _array[219];
        set => _array[219] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E220
    {
        get => _array[220];
        set => _array[220] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E221
    {
        get => _array[221];
        set => _array[221] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E222
    {
        get => _array[222];
        set => _array[222] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E223
    {
        get => _array[223];
        set => _array[223] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E224
    {
        get => _array[224];
        set => _array[224] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E225
    {
        get => _array[225];
        set => _array[225] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E226
    {
        get => _array[226];
        set => _array[226] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E227
    {
        get => _array[227];
        set => _array[227] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E228
    {
        get => _array[228];
        set => _array[228] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E229
    {
        get => _array[229];
        set => _array[229] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E230
    {
        get => _array[230];
        set => _array[230] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E231
    {
        get => _array[231];
        set => _array[231] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E232
    {
        get => _array[232];
        set => _array[232] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E233
    {
        get => _array[233];
        set => _array[233] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E234
    {
        get => _array[234];
        set => _array[234] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E235
    {
        get => _array[235];
        set => _array[235] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E236
    {
        get => _array[236];
        set => _array[236] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E237
    {
        get => _array[237];
        set => _array[237] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E238
    {
        get => _array[238];
        set => _array[238] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E239
    {
        get => _array[239];
        set => _array[239] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E240
    {
        get => _array[240];
        set => _array[240] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E241
    {
        get => _array[241];
        set => _array[241] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E242
    {
        get => _array[242];
        set => _array[242] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E243
    {
        get => _array[243];
        set => _array[243] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E244
    {
        get => _array[244];
        set => _array[244] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E245
    {
        get => _array[245];
        set => _array[245] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E246
    {
        get => _array[246];
        set => _array[246] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E247
    {
        get => _array[247];
        set => _array[247] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E248
    {
        get => _array[248];
        set => _array[248] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E249
    {
        get => _array[249];
        set => _array[249] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E250
    {
        get => _array[250];
        set => _array[250] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E251
    {
        get => _array[251];
        set => _array[251] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E252
    {
        get => _array[252];
        set => _array[252] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E253
    {
        get => _array[253];
        set => _array[253] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E254
    {
        get => _array[254];
        set => _array[254] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E255
    {
        get => _array[255];
        set => _array[255] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E256
    {
        get => _array[256];
        set => _array[256] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E257
    {
        get => _array[257];
        set => _array[257] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E258
    {
        get => _array[258];
        set => _array[258] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E259
    {
        get => _array[259];
        set => _array[259] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E260
    {
        get => _array[260];
        set => _array[260] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E261
    {
        get => _array[261];
        set => _array[261] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E262
    {
        get => _array[262];
        set => _array[262] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E263
    {
        get => _array[263];
        set => _array[263] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E264
    {
        get => _array[264];
        set => _array[264] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E265
    {
        get => _array[265];
        set => _array[265] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E266
    {
        get => _array[266];
        set => _array[266] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E267
    {
        get => _array[267];
        set => _array[267] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E268
    {
        get => _array[268];
        set => _array[268] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E269
    {
        get => _array[269];
        set => _array[269] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E270
    {
        get => _array[270];
        set => _array[270] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E271
    {
        get => _array[271];
        set => _array[271] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E272
    {
        get => _array[272];
        set => _array[272] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E273
    {
        get => _array[273];
        set => _array[273] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E274
    {
        get => _array[274];
        set => _array[274] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E275
    {
        get => _array[275];
        set => _array[275] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E276
    {
        get => _array[276];
        set => _array[276] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E277
    {
        get => _array[277];
        set => _array[277] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E278
    {
        get => _array[278];
        set => _array[278] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E279
    {
        get => _array[279];
        set => _array[279] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E280
    {
        get => _array[280];
        set => _array[280] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E281
    {
        get => _array[281];
        set => _array[281] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E282
    {
        get => _array[282];
        set => _array[282] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E283
    {
        get => _array[283];
        set => _array[283] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E284
    {
        get => _array[284];
        set => _array[284] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E285
    {
        get => _array[285];
        set => _array[285] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E286
    {
        get => _array[286];
        set => _array[286] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E287
    {
        get => _array[287];
        set => _array[287] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E288
    {
        get => _array[288];
        set => _array[288] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E289
    {
        get => _array[289];
        set => _array[289] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E290
    {
        get => _array[290];
        set => _array[290] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E291
    {
        get => _array[291];
        set => _array[291] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E292
    {
        get => _array[292];
        set => _array[292] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E293
    {
        get => _array[293];
        set => _array[293] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E294
    {
        get => _array[294];
        set => _array[294] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E295
    {
        get => _array[295];
        set => _array[295] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E296
    {
        get => _array[296];
        set => _array[296] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E297
    {
        get => _array[297];
        set => _array[297] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E298
    {
        get => _array[298];
        set => _array[298] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E299
    {
        get => _array[299];
        set => _array[299] = value;
    }

    /// <summary>Asserts that the buffer is normalized.</summary>
    [Conditional("DEBUG")]
    public void AssertNormalized()
    {
        ref var start = ref Head;
        ref readonly var end = ref Unsafe.Add(ref start, IAudioProvider.Length);

        while (Unsafe.IsAddressLessThan(start, end))
        {
            Debug.Assert(start is >= 0 and <= 1);
            start = ref Unsafe.Add(ref start, 1);
        }
    }

    /// <summary>Clones the buffer with the given label.</summary>
    /// <param name="mouth">The label.</param>
    /// <returns>The cloned buffer.</returns>
    public AudioSegment With(Sprite.Mouth mouth) => new() { _array = _array, Label = mouth - Sprite.Mouth.Upset };

    /// <summary>Clones the buffers with the given label.</summary>
    /// <param name="other">The other buffer.</param>
    /// <returns>The cloned buffers.</returns>
    public ImmutableArray<AudioSegment> With(AudioSegment other)
    {
        var result = new AudioSegment[IAudioProvider.Length];
        result[0] = this;

        for (var i = 1; i < IAudioProvider.Length; i++)
        {
            AudioSegment slice = new() { Label = Label };
            ((ReadOnlySpan<float>)_array)[..^i].CopyTo(slice._array[..^i]);
            ((ReadOnlySpan<float>)other._array)[^i..].CopyTo(slice._array[^i..]);
            result[i] = slice;
        }

        return ImmutableCollectionsMarshal.AsImmutableArray(result);
    }
}
