// <auto-generated>
// SPDX-License-Identifier: MPL-2.0
namespace Escapey.ML;

/// <summary>The input class for <see cref="HearMonitor"/>.</summary>
sealed class AudioSegment
{
    /// <summary>The inlined array.</summary>
    [InlineArray(IAudioProvider.Length)]
    public struct Array
    {
        /// <summary>The first element of the buffer.</summary>
        float _head;

        /// <inheritdoc cref="Span{T}.CopyTo"/>
        public void CopyTo(Span<float> destination) => ((ReadOnlySpan<float>)this).CopyTo(destination);
    }

    /// <summary>The inlined array.</summary>
    Array _array;

    /// <summary>Gets the first element of the buffer.</summary>
    [NoColumn]
    public ref float Head => ref _array[0];

    /// <summary>Gets or sets the normalization factor.</summary>
    public float NormalizationFactor { get; set; }

    /// <summary>Gets or sets the predicted label. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public int PredictedLabel { get; set; }

    /// <summary>Gets or sets the label. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float Label { get; set; }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E0
    {
        get => _array[0];
        set => _array[0] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E1
    {
        get => _array[1];
        set => _array[1] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E2
    {
        get => _array[2];
        set => _array[2] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E3
    {
        get => _array[3];
        set => _array[3] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E4
    {
        get => _array[4];
        set => _array[4] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E5
    {
        get => _array[5];
        set => _array[5] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E6
    {
        get => _array[6];
        set => _array[6] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E7
    {
        get => _array[7];
        set => _array[7] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E8
    {
        get => _array[8];
        set => _array[8] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E9
    {
        get => _array[9];
        set => _array[9] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E10
    {
        get => _array[10];
        set => _array[10] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E11
    {
        get => _array[11];
        set => _array[11] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E12
    {
        get => _array[12];
        set => _array[12] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E13
    {
        get => _array[13];
        set => _array[13] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E14
    {
        get => _array[14];
        set => _array[14] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E15
    {
        get => _array[15];
        set => _array[15] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E16
    {
        get => _array[16];
        set => _array[16] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E17
    {
        get => _array[17];
        set => _array[17] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E18
    {
        get => _array[18];
        set => _array[18] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E19
    {
        get => _array[19];
        set => _array[19] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E20
    {
        get => _array[20];
        set => _array[20] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E21
    {
        get => _array[21];
        set => _array[21] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E22
    {
        get => _array[22];
        set => _array[22] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E23
    {
        get => _array[23];
        set => _array[23] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E24
    {
        get => _array[24];
        set => _array[24] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E25
    {
        get => _array[25];
        set => _array[25] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E26
    {
        get => _array[26];
        set => _array[26] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E27
    {
        get => _array[27];
        set => _array[27] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E28
    {
        get => _array[28];
        set => _array[28] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E29
    {
        get => _array[29];
        set => _array[29] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E30
    {
        get => _array[30];
        set => _array[30] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E31
    {
        get => _array[31];
        set => _array[31] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E32
    {
        get => _array[32];
        set => _array[32] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E33
    {
        get => _array[33];
        set => _array[33] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E34
    {
        get => _array[34];
        set => _array[34] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E35
    {
        get => _array[35];
        set => _array[35] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E36
    {
        get => _array[36];
        set => _array[36] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E37
    {
        get => _array[37];
        set => _array[37] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E38
    {
        get => _array[38];
        set => _array[38] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E39
    {
        get => _array[39];
        set => _array[39] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E40
    {
        get => _array[40];
        set => _array[40] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E41
    {
        get => _array[41];
        set => _array[41] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E42
    {
        get => _array[42];
        set => _array[42] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E43
    {
        get => _array[43];
        set => _array[43] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E44
    {
        get => _array[44];
        set => _array[44] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E45
    {
        get => _array[45];
        set => _array[45] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E46
    {
        get => _array[46];
        set => _array[46] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E47
    {
        get => _array[47];
        set => _array[47] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E48
    {
        get => _array[48];
        set => _array[48] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E49
    {
        get => _array[49];
        set => _array[49] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E50
    {
        get => _array[50];
        set => _array[50] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E51
    {
        get => _array[51];
        set => _array[51] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E52
    {
        get => _array[52];
        set => _array[52] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E53
    {
        get => _array[53];
        set => _array[53] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E54
    {
        get => _array[54];
        set => _array[54] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E55
    {
        get => _array[55];
        set => _array[55] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E56
    {
        get => _array[56];
        set => _array[56] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E57
    {
        get => _array[57];
        set => _array[57] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E58
    {
        get => _array[58];
        set => _array[58] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E59
    {
        get => _array[59];
        set => _array[59] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E60
    {
        get => _array[60];
        set => _array[60] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E61
    {
        get => _array[61];
        set => _array[61] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E62
    {
        get => _array[62];
        set => _array[62] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E63
    {
        get => _array[63];
        set => _array[63] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E64
    {
        get => _array[64];
        set => _array[64] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E65
    {
        get => _array[65];
        set => _array[65] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E66
    {
        get => _array[66];
        set => _array[66] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E67
    {
        get => _array[67];
        set => _array[67] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E68
    {
        get => _array[68];
        set => _array[68] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E69
    {
        get => _array[69];
        set => _array[69] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E70
    {
        get => _array[70];
        set => _array[70] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E71
    {
        get => _array[71];
        set => _array[71] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E72
    {
        get => _array[72];
        set => _array[72] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E73
    {
        get => _array[73];
        set => _array[73] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E74
    {
        get => _array[74];
        set => _array[74] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E75
    {
        get => _array[75];
        set => _array[75] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E76
    {
        get => _array[76];
        set => _array[76] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E77
    {
        get => _array[77];
        set => _array[77] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E78
    {
        get => _array[78];
        set => _array[78] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E79
    {
        get => _array[79];
        set => _array[79] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E80
    {
        get => _array[80];
        set => _array[80] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E81
    {
        get => _array[81];
        set => _array[81] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E82
    {
        get => _array[82];
        set => _array[82] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E83
    {
        get => _array[83];
        set => _array[83] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E84
    {
        get => _array[84];
        set => _array[84] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E85
    {
        get => _array[85];
        set => _array[85] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E86
    {
        get => _array[86];
        set => _array[86] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E87
    {
        get => _array[87];
        set => _array[87] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E88
    {
        get => _array[88];
        set => _array[88] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E89
    {
        get => _array[89];
        set => _array[89] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E90
    {
        get => _array[90];
        set => _array[90] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E91
    {
        get => _array[91];
        set => _array[91] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E92
    {
        get => _array[92];
        set => _array[92] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E93
    {
        get => _array[93];
        set => _array[93] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E94
    {
        get => _array[94];
        set => _array[94] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E95
    {
        get => _array[95];
        set => _array[95] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E96
    {
        get => _array[96];
        set => _array[96] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E97
    {
        get => _array[97];
        set => _array[97] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E98
    {
        get => _array[98];
        set => _array[98] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E99
    {
        get => _array[99];
        set => _array[99] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E100
    {
        get => _array[100];
        set => _array[100] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E101
    {
        get => _array[101];
        set => _array[101] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E102
    {
        get => _array[102];
        set => _array[102] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E103
    {
        get => _array[103];
        set => _array[103] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E104
    {
        get => _array[104];
        set => _array[104] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E105
    {
        get => _array[105];
        set => _array[105] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E106
    {
        get => _array[106];
        set => _array[106] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E107
    {
        get => _array[107];
        set => _array[107] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E108
    {
        get => _array[108];
        set => _array[108] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E109
    {
        get => _array[109];
        set => _array[109] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E110
    {
        get => _array[110];
        set => _array[110] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E111
    {
        get => _array[111];
        set => _array[111] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E112
    {
        get => _array[112];
        set => _array[112] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E113
    {
        get => _array[113];
        set => _array[113] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E114
    {
        get => _array[114];
        set => _array[114] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E115
    {
        get => _array[115];
        set => _array[115] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E116
    {
        get => _array[116];
        set => _array[116] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E117
    {
        get => _array[117];
        set => _array[117] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E118
    {
        get => _array[118];
        set => _array[118] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E119
    {
        get => _array[119];
        set => _array[119] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E120
    {
        get => _array[120];
        set => _array[120] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E121
    {
        get => _array[121];
        set => _array[121] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E122
    {
        get => _array[122];
        set => _array[122] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E123
    {
        get => _array[123];
        set => _array[123] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E124
    {
        get => _array[124];
        set => _array[124] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E125
    {
        get => _array[125];
        set => _array[125] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E126
    {
        get => _array[126];
        set => _array[126] = value;
    }

    /// <summary>Gets or sets the exact element. Not meant to be used directly, but for the model.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public float E127
    {
        get => _array[127];
        set => _array[127] = value;
    }

    /// <summary>Asserts that the buffer is normalized.</summary>
    [Conditional("DEBUG")]
    public void AssertNormalized()
    {
        ref var start = ref Head;
        ref readonly var end = ref Unsafe.Add(ref start, IAudioProvider.Length);

        while (Unsafe.IsAddressLessThan(start, end))
        {
            Debug.Assert(start is >= 0 and <= 1);
            start = ref Unsafe.Add(ref start, 1);
        }
    }

    /// <summary>Clones the buffer with the given label.</summary>
    /// <param name="mouth">The label.</param>
    /// <returns>The cloned buffer.</returns>
    public AudioSegment With(Sprite.Mouth mouth) => new() { _array = _array, Label = mouth - Sprite.Mouth.Upset };

    /// <summary>Clones the buffers with the given label.</summary>
    /// <param name="other">The other buffer.</param>
    /// <returns>The cloned buffers.</returns>
    public ImmutableArray<AudioSegment> With(AudioSegment other)
    {
        var result = new AudioSegment[IAudioProvider.Length];
        result[0] = this;

        for (var i = 1; i < IAudioProvider.Length; i++)
        {
            AudioSegment slice = new() { Label = Label };
            ((ReadOnlySpan<float>)_array)[..^i].CopyTo(slice._array[..^i]);
            ((ReadOnlySpan<float>)other._array)[^i..].CopyTo(slice._array[^i..]);
            result[i] = slice;
        }

        return ImmutableCollectionsMarshal.AsImmutableArray(result);
    }
}
