// SPDX-License-Identifier: LicenseRef-PolyForm-Strict
namespace Escapey.Providers.Audio;

partial class AudioProvider
{
    /// <summary>Provides audio implementation with PipeWire.</summary>
    // ReSharper disable once ArrangeTypeMemberModifiers
    private sealed partial class PipeWire : AudioProvider
    {
        /// <summary>The library name to link against.</summary>
        const string Lib = "libpipewire-0.3.so.0";

        /// <summary>The options for the task that invokes the PipeWire library.</summary>
        const TaskCreationOptions Options = TaskCreationOptions.LongRunning;

        /// <summary>Whether this class has ever been successfully instantiated.</summary>
        static bool s_initialized;

        /// <summary>The singleton instance.</summary>
        /// <remarks><para>
        /// This class was originally designed not to be a singleton, however after two weeks of debugging, it proved to
        /// be too difficult. The current behavior of this implementation causes a segmentation fault if instantiated
        /// twice, therefore the singleton acts more as a band-aid to this problem. As a result, if the singleton is
        /// ever used, a stream and thread loop is kept alive even if the singleton isn't used and disposed, until
        /// the process exits. Fortunately, in most scenarios the singleton is either always used or never.
        /// </para></remarks>
        static PipeWire? s_pw;

        /// <summary>The pointer to the stack-allocated <see cref="State"/> within the <see cref="_task"/>.</summary>
        /// <remarks><para>
        /// Do not dereference this pointer if the <see cref="_task"/> returns <see langword="true"/>
        /// for <see cref="Task.IsCompleted"/>. Only the first element may be dereferenced.
        /// </para></remarks>
        unsafe State* _state;

        /// <summary>The task that runs the PipeWire library.</summary>
        Task _task = Task.CompletedTask;

        /// <summary>Initializes a new instance of the <see cref="AudioProvider.PipeWire"/> class.</summary>
        PipeWire() { }

        /// <inheritdoc />
        public override AudioSegment Segment { get; } = new();

        /// <summary>The error message displayed when running on big-endian architecture.</summary>
        static string NoBigEndian =>
            "PipeWire can only be used on little-endian architectures. If you want me to support it, " +
            $"please send a big-endian version of this spa_pod blob: {Convert.ToHexString(StreamParameterBlob)}";

        /// <summary>Contains the little-endian binary representation of the PipeWire stream parameters.</summary>
        /// <remarks><para>
        /// Autogenerated with the following C code:
        /// </para>
        /// <code language="c">
        /// #include &lt;spa/param/audio/raw-utils.h&gt;
        /// uint8_t buffer[1024] = {};
        /// struct spa_pod_builder b = {buffer, sizeof(buffer)};
        /// const struct spa_audio_info_raw info = {
        ///     .format = SPA_AUDIO_FORMAT_F32,
        ///     .rate = 48000,
        ///     .channels = 1,
        /// };
        /// const auto param = spa_format_audio_raw_build(&amp;b, SPA_PARAM_EnumFormat, &amp;info);
        /// </code>
        /// </remarks>
        static ReadOnlySpan<byte> StreamParameterBlob =>
        [
            160, 0, 0, 0, 15, 0, 0, 0, 3, 0, 4, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 3, 0, 0, 0,
            1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
            1, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 3, 0, 0, 0, 27, 1, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0,
            4, 0, 0, 0, 4, 0, 0, 0, 128, 187, 0, 0, 0, 0, 0, 0, 4, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0,
            1, 0, 0, 0, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, 0, 0, 12, 0, 0, 0, 13, 0, 0, 0, 4, 0, 0, 0, 3, 0, 0, 0,
        ];

        /// <summary>Gets the singleton instance.</summary>
        /// <param name="warnings">The warnings.</param>
        /// <returns>The instance.</returns>
        [MustUseReturnValue]
        public static PipeWire Instance(out ImmutableArray<Exception> warnings)
        {
            s_pw ??= new();

            if (!BitConverter.IsLittleEndian && (warnings = [new PlatformNotSupportedException(NoBigEndian)]) is var _)
                return s_pw;

            if (!s_initialized)
            {
                if (Go(Init, out var e) && (warnings = [e]) is var _)
                    return s_pw;

                s_initialized = true;
                AppDomain.CurrentDomain.ProcessExit += Deinit;
                s_pw._task = Task.Factory.StartNew(s_pw.Run, CancellationToken.None, Options, TaskScheduler.Default);
            }

            warnings = [];
            return s_pw;
        }

        /// <inheritdoc />
        public override void Dispose() { }

        /// <inheritdoc />
        [MustUseReturnValue]
        public override AudioSegment? Poll()
        {
            if (PollRaw() is not { IsEmpty: false } current)
                return null;

            var real = ArrayPool<float>.Shared.Rent(Length);

            try
            {
                current.CopyTo(real);
                Segment.Forward(real.AsSpan().UnsafelyTake(Length));
                return Segment;
            }
            finally
            {
                ArrayPool<float>.Shared.Return(real);
            }
        }

        /// <inheritdoc />
        [MustUseReturnValue]
        public override unsafe Span<float> PollRaw() =>
            _task.IsCompleted ? _task.Exception is { } e ? throw e : [] : State.Current(_state);

        /// <summary>
        /// Deinitializes PipeWire. This indirection is required to make <see cref="DllNotFoundException"/> catchable.
        /// </summary>
        [MethodImpl(MethodImplOptions.NoInlining)]
        static unsafe void Deinit(object? _, EventArgs __)
        {
            if (s_pw is not null)
            {
                s_pw._state->Stop();
                s_pw._task.Wait();
            }

            DeinitUnsafe();
        }

        /// <summary>
        /// Initializes PipeWire. This indirection is required to make <see cref="DllNotFoundException"/> catchable.
        /// </summary>
        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Init() => InitUnsafe(0, 0);

        /// <summary>Calls the PipeWire library.</summary>
        unsafe void Run() => State.Run(out _state);

        [LibraryImport(Lib, EntryPoint = "pw_deinit")]
        private static partial void DeinitUnsafe();

        [LibraryImport(Lib, EntryPoint = "pw_init")]
        private static partial void InitUnsafe(nint argc, nint argv);
    }
}
